"""move source to summary

Revision ID: 2f0988fc4261
Revises: 37e06c3283a8
Create Date: 2023-06-21 01:13:04.886789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0988fc4261'
down_revision = '37e06c3283a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
