"""move source to summary to

Revision ID: 4ebdafcc6ad6
Revises: b43de229e99a
Create Date: 2023-06-21 01:26:03.692351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebdafcc6ad6'
down_revision = 'b43de229e99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('summary', sa.String(length=256), nullable=True))
    op.drop_column('film', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('source', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('film', 'summary')
    # ### end Alembic commands ###
